version: '3.7'
services:
    postgresql:
        image: postgres:10-alpine
        container_name: postgresql10-box
        volumes:
            # NOTE: for Windows host path must be written down like this
            - //E/docker/volumes/postgres10:/var/lib/postgresql
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
        ports:
            - 5432:5432
