
version: '3.7'

services:
    postgresql:
        image: postgres:10-alpine
        container_name: postgresql10-box
        volumes:
            - postgres_data:/var/lib/postgresql
        environment:
            - POSTGRES_USER=pguser
            - POSTGRES_PASSWORD=pgpass
        ports:
            - 5432:5432
        # Uncomment line below to enable statement logging
        #command: ["postgres", "-c", "log_statement=all"]

volumes:
    postgres_data:
