
services:
  
  oracle:
    image: gvenzl/oracle-free:23
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: s3cr3t!  # Set the password for the SYS, SYSTEM and PDBADMIN users
      # APP_USER: bernie
      # APP_USER_PASSWORD: lomax
    # Mount a local SQL file to initialize your schema at startup
    volumes:
      - ./db_initialization/init.sql:/container-entrypoint-initdb.d/my-init.sql:ro