version: '3'
services:
  opensearch:
    image: opensearchproject/opensearch:2.8.0
    ports:
      - 9200:9200
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true

volumes:
  opensearch_data:
