
version: '3'

services:

    koillection:
        image: koillection/koillection:1.6.8
        container_name: koillection
        restart: unless-stopped
        ports:
            - 8087:80
        env_file:
            - .env
        depends_on:
            - db
        volumes:
            - ./volumes/koillection/uploads:/uploads

    db:
        image: postgres:16
        container_name: db
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - "./volumes/postgresql:/var/lib/postgresql/data"

